version: 2.1

workflows:
  main:
    jobs:
      - buildProduction:
          filters:
            branches:
              only: master
      - buildStaging:
          filters:
            branches:
              ignore: master
      - deployProduction:
          requires:
            - buildProduction
          filters:
            branches:
              only: master
      - deployStaging:
          requires:
            - buildStaging
          filters:
            branches:
              ignore: master
jobs:
  buildProduction:
    docker:
      - image: hubci/gotham:0.13
    steps:
      - checkout
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production gotham -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public
  buildStaging:
    docker:
      - image: hubci/gotham:0.13
    steps:
      - checkout
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=staging gotham -v -s src/ --config config.yml,staging-config.yml
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public
  deployProduction:
    docker:
      - image: hubci/gotham:0.13
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run: |
          echo 'sweb0.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHyIA/VJN9GHUeYUvauk+sGsQcvk8FpXErixwvgqQmW1pdje/Vo4RyAAskzdgoR+HUYOWM1gLW7ZFZHL8F//sqw=' >> ~/.ssh/known_hosts
          rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/thereserveforce/www/public_html
  deployStaging:
    docker:
      - image: hubci/gotham:0.13
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run: |
          echo 'sweb0.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHyIA/VJN9GHUeYUvauk+sGsQcvk8FpXErixwvgqQmW1pdje/Vo4RyAAskzdgoR+HUYOWM1gLW7ZFZHL8F//sqw=' >> ~/.ssh/known_hosts
          rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/thereserveforce/staging-www/public_html
