version: 2.1

workflows:
  main:
    jobs:
      - buildProduction:
          filters:
            branches:
              only: trunk
      - deployProduction:
          requires:
            - buildProduction
          filters:
            branches:
              only: trunk
jobs:
  buildProduction:
    docker:
      - image: hubci/strawberry:0.22.0
    steps:
      - checkout
      - run:
          name: "Build Website With Hugo"
          command: HUGO_ENV=production strawberry -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public
  deployProduction:
    docker:
      - image: hubci/strawberry:0.22.0
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run:
          name: "Deploy to Revidian Cloud"
          command: |
            echo 'web0.atl.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE16slz1okRPeUhxIpzBCn9rHqjk51ylxEYlYXvblswcxOQ0rPyAX6N8Bd2pnsh99xce/jaX2KJHPLPCc+zAXTg=' >> ~/.ssh/known_hosts
            rsync -va --delete src/public/ root@web0.atl.revidian.net:/gfs-vols/static-vol/thereserveforce/www/public_html
