apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: static-websites
  name: trf-website
  labels:
    app: trf-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trf-website
  template:
    metadata:
      labels:
        app: trf-website
    spec:
      containers:
      - name: trf-website
        image: "ghcr.io/thereserveforce/www.thereserveforce.com:trunk"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: static-websites
  name: trf-website
  labels:
    app: trf-website
spec:
  type: ClusterIP
  selector:
    app: trf-website
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: static-websites
  name: trf-website
  labels:
    app: trf-website
spec:
  ingressClassName: caddy
  rules:
  - host: www.thereserveforce.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: trf-website
            port:
              number: 80
  - host: thereserveforce.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: trf-website
            port:
              number: 80
